package com.triquang.entity;
// Generated Jun 19, 2022, 6:02:22 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "online_banking", uniqueConstraints = @UniqueConstraint(columnNames = "Email"))
@NamedQueries({
	@NamedQuery(name = "Account.findAll", query = "SELECT a FROM Account a ORDER BY a.fullname DESC"),
	@NamedQuery(name = "Account.findByEmail", query = "SELECT a FROM Account a WHERE a.email = :email"),
	@NamedQuery(name = "Account.countAll", query = "SELECT COUNT(a.email) FROM Account a"),
	@NamedQuery(name = "Account.checkLogin", query = "SELECT a FROM Account a WHERE a.email = :email AND a.password = :password")
})
public class Account implements java.io.Serializable {

	private Integer accId;
	private String username;
	private String password;
	private String fullname;
	private String email;
	private String phone;
	private double balance;
	private Set<Transactiondetails> transactiondetailses = new HashSet<Transactiondetails>(0);

	public Account() {
	}

	public Account(String username, String password, String fullname, String email, String phone, double balance) {
		this.username = username;
		this.password = password;
		this.fullname = fullname;
		this.email = email;
		this.phone = phone;
		this.balance = balance;
	}

	public Account(String username, String password, String fullname, String email, String phone, double balance,
			Set<Transactiondetails> transactiondetailses) {
		this.username = username;
		this.password = password;
		this.fullname = fullname;
		this.email = email;
		this.phone = phone;
		this.balance = balance;
		this.transactiondetailses = transactiondetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AccID", unique = true, nullable = false)
	public Integer getAccId() {
		return this.accId;
	}

	public void setAccId(Integer accId) {
		this.accId = accId;
	}

	@Column(name = "Username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Password", nullable = false, length = 64)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Fullname", nullable = false, length = 45)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "Email", unique = true, nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Phone", nullable = false, length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Balance", nullable = false, precision = 22, scale = 0)
	public double getBalance() {
		return this.balance;
	}

	public void setBalance(double balance) {
		this.balance = balance;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Transactiondetails> getTransactiondetailses() {
		return this.transactiondetailses;
	}

	public void setTransactiondetailses(Set<Transactiondetails> transactiondetailses) {
		this.transactiondetailses = transactiondetailses;
	}

}
