package com.triquang.entity;
// Generated Jun 19, 2022, 6:02:22 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transactiondetails generated by hbm2java
 */
@Entity
@Table(name = "transactiondetails", catalog = "online_banking")
@NamedQueries({
		@NamedQuery(name = "Transactiondetails.findAll", query = "SELECT td FROM Transactiondetails td ORDER BY td.dateOfTrans DESC"),
		@NamedQuery(name = "Transactiondetails.countAll", query = "SELECT COUNT(*) FROM Transactiondetails"),
		@NamedQuery(name = "Transactiondetails.findBytransType", query = "SELECT t FROM Transactiondetails t WHERE t.transType = :transType"),
		@NamedQuery(name = "Transactiondetails.findByIdAndAccount", query = "SELECT td FROM Transactiondetails td WHERE td.transId =:transId AND td.account.accId =:accId"),
		@NamedQuery(name = "Transactiondetails.search", query = "SELECT t FROM Transactiondetails t WHERE t.transType LIKE '%' || :keyword || '%'") })
public class Transactiondetails implements java.io.Serializable {

	private Integer transId;
	private Account account;
	private double transMoney;
	private Integer transType;
	private Date dateOfTrans;

	public Transactiondetails() {
	}

	public Transactiondetails(Account account, double transMoney, Integer transType, Date dateOfTrans) {
		this.account = account;
		this.transMoney = transMoney;
		this.transType = transType;
		this.dateOfTrans = dateOfTrans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TransID", unique = true, nullable = false)
	public Integer getTransId() {
		return this.transId;
	}

	public void setTransId(Integer transId) {
		this.transId = transId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "AccID", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "TransMoney", nullable = false, precision = 22, scale = 0)
	public double getTransMoney() {
		return this.transMoney;
	}

	public void setTransMoney(double transMoney) {
		this.transMoney = transMoney;
	}

	@Column(name = "TransType", nullable = false, length = 11)
	public Integer getTransType() {
		return this.transType;
	}

	public void setTransType(Integer transType) {
		this.transType = transType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateOfTrans", nullable = false, length = 10)
	public Date getDateOfTrans() {
		return this.dateOfTrans;
	}

	public void setDateOfTrans(Date dateOfTrans) {
		this.dateOfTrans = dateOfTrans;
	}

}
